# Generated by Django 3.2.16 on 2024-01-19 11:17

from django.db import migrations

from core.utils import remove_role_right_for_system, insert_role_right_for_system


REPORT_NHIA_CLAIMS_PAID_RIGHT = 131230
REPORT_NHIA_CLAIMS_REJECTED_RIGHT = 131231
REPORT_NHIA_CLAIMS_PENDING_RIGHT = 131232
NHIA_REPORT_RIGHTS = [
    REPORT_NHIA_CLAIMS_PAID_RIGHT,
    REPORT_NHIA_CLAIMS_REJECTED_RIGHT,
    REPORT_NHIA_CLAIMS_PENDING_RIGHT
]
SYSTEM_ROLE = 64


def add_nhia_report_rights(apps, schema_editor):
    """
    Add nhia report rights to the IMIS Administrator.
    """
    for right in NHIA_REPORT_RIGHTS:
        insert_role_right_for_system(SYSTEM_ROLE, right)


def remove_nhia_reports_rights(apps, schema_editor):
    """
    Remove nhia report rights to the IMIS Administrator.
    """
    for right in NHIA_REPORT_RIGHTS:
        remove_role_right_for_system(SYSTEM_ROLE, right)


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0017_set_managed_to_true'),
    ]

    operations = [
        migrations.RunPython(add_nhia_report_rights, remove_nhia_reports_rights),
    ]
