# Generated by Django 3.2.16 on 2023-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0017_set_managed_to_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(db_column='ClaimCode', max_length=50, unique=True),
        ),
    ]
