# Generated by Django 3.2.16 on 2024-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_add_nhia_claim_reports_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(db_column='ClaimCode', max_length=100, blank=True, null=True),
        ),
    ]
