# Generated by Django 3.2.16 on 2024-06-07 15:33

from django.db import migrations

from core.utils import insert_role_right_for_system, remove_role_right_for_system


REPORT_NHIA_CLAIM_DETAILS_RIGHT = 131235
SYSTEM_ROLE = 64


def add_nhia_report_rights(apps, schema_editor):
    """
    Add nhia report rights to the IMIS Administrator.
    """
    insert_role_right_for_system(SYSTEM_ROLE, REPORT_NHIA_CLAIM_DETAILS_RIGHT)


def remove_nhia_reports_rights(apps, schema_editor):
    """
    Remove nhia report rights to the IMIS Administrator.
    """
    remove_role_right_for_system(SYSTEM_ROLE, REPORT_NHIA_CLAIM_DETAILS_RIGHT)


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0019_alter_claim_code'),
    ]

    operations = [
        migrations.RunPython(add_nhia_report_rights, remove_nhia_reports_rights),
    ]
