# Generated by Django 3.2.25 on 2025-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0021_split_claim_update_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='type',
            field=models.CharField(blank=True, db_column='ClaimType', max_length=36, null=True),
        ),
    ]
