# Generated by Django 3.2.25 on 2025-05-25 11:31

import core.fields
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0022_claim_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTest',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.AutoField(db_column='ClaimID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ClaimUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('status', models.CharField(blank=True, db_column='ClaimStatus', max_length=36, null=True)),
            ],
            options={
                'db_table': 'tblClaimTest',
                'managed': True,
            },
        ),
    ]
