# Generated by Django 3.2.25 on 2025-05-25 11:38

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0023_claimtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimtest',
            name='validity_from',
            field=core.fields.DateTimeField(blank=True, db_column='ValidityFrom', null=True),
        ),
    ]
