# Generated by Django 3.2.25 on 2025-05-26 13:09

import core.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0024_alter_claimtest_validity_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimtest',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
    ]
