# Generated by Django 3.2.25 on 2025-06-07 10:28

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_insuree_is_formal_sector'),
        ('location', '0016_alter_healthfacility_code'),
        ('claim', '0025_alter_claimtest_validity_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalClaim',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.AutoField(db_column='ClaimID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ClaimUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('category', models.CharField(blank=True, db_column='ClaimCategory', max_length=1, null=True)),
                ('code', models.CharField(blank=True, db_column='ClaimCode', max_length=100, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('health_facility', models.ForeignKey(db_column='HFID', on_delete=django.db.models.deletion.DO_NOTHING, to='location.healthfacility')),
                ('insuree', models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
            ],
            options={
                'db_table': 'tblAdditionalClaim',
                'managed': True,
            },
        ),
    ]
