# Generated by Django 3.2.25 on 2025-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0026_additionalclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalclaim',
            name='category',
            field=models.CharField(blank=True, db_column='ClaimCategory', max_length=100, null=True),
        ),
    ]
